### ISSUE TITLE
Roadmap V0.0.1

### ISSUE THREAD

**Issue by jistiak** [jistiak/aika#2]
Tasks for the week long [OpenAI Hackathon](https://lablab.ai/event/openai-hackathon) for developing initial prototype:  

### Technical tasks

- [x] Recipe accept or not - user input @jistiak 
- [x] Remaining ingredients calculation @jakaria-nawaz 
- [x] From text output, extract the ingredients - using regex @jakaria-nawaz 
- [x] Unit mapping and conversion script @ShariarImroze 
- [x] Save recipe button @jistiak 
- [ ] Adding back-end codes for Redis to  save recipes to database @jakaria-nawaz 
- [ ] Adding the saved recipe to recipes page (Pull from Redis + display) @jistiak 
- [ ] Inventory search and filter options @jakaria-nawaz 
- [x] Adding visualization in inventory page @ShariarImroze 
- [ ] Adding Dall-e image in saved recipe page @ShariarImroze 
- [x] Shopping list creation @jistiak  
- [x] Add input option to- Manually input data @jistiak 

### Business prospect:

- [ ] Market survey template design and planning
- [x] Business Model Canvas
